version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r blue_green/app/requirements.txt
  pre_build:
    commands:
      - python -m unittest discover blue_green/app/tests
  build:
    commands:
      - zip -r app.zip .
artifacts:
  files:
    - app.zip